use_frameworks!

platform :ios, '8.0'

target 'SKTargetAction_Example' do
  pod 'SKTargetAction', :path => '../'

  target 'SKTargetAction_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
